name: Build on pull request to master or a feature branch

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set NODE_OPTIONS env variable
        run: echo "NODE_OPTIONS=--max-old-space-size=8192" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: lint code
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
