name: Build on pull request to main or a feature branch

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set NODE_OPTIONS env variable
        run: echo "NODE_OPTIONS=--max-old-space-size=8192" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn lint
